### ISSUE TITLE
Errors in c360-sample

### ISSUE THREAD

**Issue by bongiova61** [D3Automation/angular2-c360-sample#1]
I downloaded and installed the sample from git (master), but I see compilation errors: i.e. in part-resolver.service.ts method .c360Context.getNewModel() should return an observable (based on declaration files) but is used as a Promise.
I suspect a misalignment between this app and the angular2-c360 library...

**Comment by bencameron** [comment]
Thanks for reporting the issue.  Looks like the change to the library and the sample app were made around the same time, but then the updated version of the library didn't get pushed to npm.  I'll get that fixed later today or sometime this weekend.

**Comment by bongiova61** [comment]
I was able to solve the problem changing "angular2-c360" version from 0.1.0 to 0.2.0 in package.json

**Comment by bencameron** [comment]
Cool.  I have pushed that same change now.  I'll close this issue, but I noticed [another issue](https://github.com/D3Automation/angular2-c360-sample/issues/2) after fixing it that I am working on now.
