### ISSUE TITLE
Show a specific property (or properties) Not Working

### ISSUE THREAD

**Issue by AppliedDesignIntelligence** [D3Automation/angular2-c360-sample#3]
Showing single properties does not work. It shows a blank router outlet

![image](https://cloud.githubusercontent.com/assets/22031133/21597521/a3c9febe-d111-11e6-9f2c-d5c51ddbc455.png)

This worked just fine in the Angular 1 version

**Comment by bencameron** [comment]
Looks like the html for referencing specific properties was not updated when the property in the component's class was renamed (was "rootPart" -- now "part").  Updating "rootPart.Building_Height" to "part.Building_Height" (and same with other property and ngIf on containing div) will fix the problem.

I've made these changes pushed to the master branch.
